<?php Flasher::flash(); ?>
<h1>LOGIN</h1>
<form action="<?= BASEURL; ?>/auth/processLogin" method="POST">
    <div>
        <label for="email">Email</label>
        <input type="email" id="email" name="email">
        <?php Validator::showError('email'); ?>
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="password">
        <?php Validator::showError('password'); ?>
    </div>
    <button type="submit">Login</button>
</form>