<?php Flasher::flash(); ?>
<h1>REGISTER</h1>
<form action="<?= BASEURL; ?>/auth/processRegister" method="POST">
    <div>
        <label for="email">Email</label>
        <input type="email" id="email" name="email">
        <?php Validator::showError('email'); ?>
    </div>
    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="name">
        <?php Validator::showError('name'); ?>
    </div>

    <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="password">
        <?php Validator::showError('password'); ?>
    </div>
    <div>
        <label for="confirm_password">Confirm Password</label>
        <input type="password" id="password" name="confirm_password">
        <?php Validator::showError('confirm_password'); ?>
    </div>
    <button type="submit">Register</button>
</form>