<h1><?= $data['category']['name']; ?></h1>

<?php Flasher::flash(); ?>

<?php foreach( $data['items'] as $item ): ?>
    <ul>
        <li>Name: <?= $item['name']; ?></li>
        <li>Name: <?= $item['description']; ?></li>
        <li>Name: <?= $item['price']; ?></li>
        <li>Name: <?= $item['img_name']; ?></li>
        <form action="<?= BASEURL ?>/order/detail_add/<?= $data['category']['id']; ?>/<?= $item['id']; ?>">
            <button type="submit">add to order</button>
        </form>

    </ul>
<?php endforeach ?>