<section>
    <div class="container py-5">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <span class="heading">
                    <h2>CHOOSE CATEGORY</h2>
                </span>
            </div>
        </div>
        <!-- TODO: make these manual instead, add the pictures -->
        <?php foreach ($data['categories'] as $category) : ?>
            <div class="row d-flex justify-content-center mb-4">
                <a href="<?= BASEURL; ?>/menu/category/<?= $category['id']; ?>" class="col-11 col-lg-9 category m-0 shadow">
                    <h2><?= $category['name']; ?></h2>
                </a>
            </div>
        <?php endforeach ?>
    </div>
</section>