<footer class="py-5">
    <div class="container">
        <h5 class="text-center">CONNECT WITH US</h5>
        <div class="d-flex justify-content-center">
            <a href="https://www.instagram.com/alambistroncafe/" class="footer-icon"><i class="bi bi-instagram"></i></a>
            <a href="https://www.facebook.com/ALAMbistrocafe/" class="footer-icon"><i class="bi bi-facebook"></i></a>
            <a href="https://wa.me/6281319433133?text=" class="footer-icon"><i class="bi bi-whatsapp"></i></a>
        </div>
    </div>

</footer>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
<script src="<?= BASEURL; ?>/js/bootstrap.js"></script>
</body>

</html>