    <footer class="footer mt-auto py-3 bg-light">
        <ul>
            <li>ID: <?= Auth::userId(); ?></li>
            <li>User: <?= $_SESSION['user'] ?></li>
            <li>Role: <?= $_SESSION['role'] ?></li>
            <li>Flasher: <?= $_SESSION['flash'] ?></li>
        </ul>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script src="<?= BASEURL; ?>/js/bootstrap.js"></script>
    </body>

    </html>