<div class="d-flex flex-column flex-shrink-0 px-3 py-4 text-white bg-dark position-fixed" style="width: 280px; height:100%">
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="<?= BASEURL; ?>/admin/orders" class="nav-link text-white" aria-current="page">
                <i class="bi bi-card-list me-3" style="font-size: 1.5rem;"></i>
                Orders
            </a>
        </li>
        <li>
            <a href="<?= BASEURL; ?>/admin/messages" class="nav-link text-white">
                <i class="bi bi-chat-dots me-3" style="font-size: 1.5rem;"></i>
                Messages
            </a>
        </li>
        <hr>
        <li>
            <a href="<?= BASEURL; ?>/admin/menu" class="nav-link active">
                <i class="bi bi-journals me-3" style="font-size: 1.5rem;"></i>
                Manage Menu
            </a>
        </li>
    </ul>
</div>

<section>

    <span class="admin-heading">Manage Menu</span>

    <div class="row">
        <div class="col-4">
            <div class="card mt-3" style="min-width: 355px;">
                <div class="card-ab-header">
                    <h5>Edit Item Details</h5>
                </div>
                <div class="card-body">
                    <form action="<?= BASEURL ?>/admin/menu_update/<?= $data['item']['id'] ?>/" method="POST" enctype="multipart/form-data">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="name" id="name" placeholder="Item Name" value="<?= $data['item']['name'] ?>">
                            <label for="name">Name</label>
                            <div class="text-danger mt-1">
                                <?php Validator::showError('name'); ?>
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <textarea class="form-control" name="description" id="description" placeholder="Item Description" style="height: 100px;"><?= $data['item']['description'] ?></textarea>
                            <label for="description">Description</label>
                            <div class="text-danger mt-1">
                                <?php Validator::showError('description'); ?>
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <select name="category_id" id="category_id" class="form-select">
                                <?php foreach ($data['categories'] as $category) : ?>
                                    <option value="<?= $category['id'] ?>" <?php if ($data['item']['category_id'] == $category['id']) : ?>selected<?php endif ?>><?= $category['name'] ?></option>
                                <?php endforeach ?>
                            </select>
                            <label for="category_id">Category</label>
                            <div class="text-danger mt-1">
                                <?php Validator::showError('category_id'); ?>
                            </div>
                        </div>
                        <div class="input-group">
                            <span class="input-group-text" id="price">Rp.</span>
                            <input type="text" name="price" class="form-control" placeholder="Price" aria-label="price" aria-describedby="price" value="<?= $data['item']['price'] ?>">
                        </div>
                        <div class=" text-danger mt-1">
                            <?php Validator::showError('price'); ?>
                        </div>
                        <div class="mt-3 mb-5">
                            <label for="image" class="form-label">Upload Image</label>
                            <input type="file" name="image" id="image" class="form-control">
                            <div class="text-danger mt-1">
                                <?php Validator::showError('image'); ?>
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            <a href="<?= BASEURL ?>/admin/menu" class="btn btn-ab-square-light m-2">Cancel</a>
                            <button type="submit" class="btn btn-ab-square m-2">Save Details</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>