<div class="d-flex flex-column flex-shrink-0 px-3 py-4 text-white bg-dark position-fixed" style="width: 280px; height:100%">
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="<?= BASEURL; ?>/admin/orders" class="nav-link text-white" aria-current="page">
                <i class="bi bi-card-list me-3" style="font-size: 1.5rem;"></i>
                Orders
            </a>
        </li>
        <li>
            <a href="<?= BASEURL; ?>/admin/messages" class="nav-link text-white">
                <i class="bi bi-chat-dots me-3" style="font-size: 1.5rem;"></i>
                Messages
            </a>
        </li>
        <hr>
        <li>
            <a href="<?= BASEURL; ?>/admin/menu" class="nav-link active">
                <i class="bi bi-journals me-3" style="font-size: 1.5rem;"></i>
                Manage Menu
            </a>
        </li>
    </ul>
</div>

<section>

    <span class="admin-heading">Manage Menu</span>

    <?php Flasher::flash(); ?>

    <div class="row">
        <div class="col-8">
            <div class="card mt-3">
                <div class="card-ab-header d-flex">
                    <form action="<?= BASEURL ?>/admin/menu_search/" method="POST" class="d-flex me-auto">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search menu..." aria-label="Search">
                        <button class="btn btn-link" type="submit" style="padding: 0px; font-size: 1.5rem; color:gray"><i class="bi bi-search"></i></button>
                    </form>
                    <div class="dropdown">
                        <a href="#" class="btn btn-outline-secondary dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-filter me-2"></i>
                            <?php if (isset($data['filter'])) : ?>
                                <?= $data['filter'] ?>
                            <?php else : ?>
                                Category
                            <?php endif ?>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="<?= BASEURL ?>/admin/menu">No filter</a></li>
                            <?php foreach ($data['categories'] as $category) : ?>
                                <li><a class="dropdown-item" href="<?= BASEURL ?>/admin/menu_filter/<?= $category['id'] ?>"><?= $category['name'] ?></a></li>
                            <?php endforeach ?>
                        </ul>
                    </div>

                </div>
                <div class="card-body" style="min-height: 70vh;">
                    <?php if (isset($data['query'])) : ?>
                        <div class="mb-2">
                            Showing results for "<?= $data['query'] ?>"...
                        </div>
                    <?php endif ?>
                    <table class="table align-middle mb-0 bg-white">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Price (Rp)</th>
                                <th style="width: 10%;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($data['items'] as $item) : ?>
                                <tr>
                                    <td class="py-3">
                                        <?= $item['name']; ?>
                                    </td>
                                    <td class="py-3">
                                        <?= $data['cat_names'][$item['category_id']]; ?>
                                    </td>
                                    <td class="py-3">
                                        <?php echo number_format($item['price']); ?>
                                    </td>
                                    <td>
                                        <div class="d-flex justify-content-end">
                                            <form action="<?= BASEURL ?>/admin/menu_details/<?= $item['id'] ?>/" method="POST">
                                                <button class="btn btn-edit mb-0 me-2"><i class="bi bi-pencil-square"></i></button>
                                            </form>

                                            <form action="<?= BASEURL ?>/admin/menu_delete/<?= $item['id'] ?>/" method="POST">
                                                <button type="submit" class="btn btn-edit mb-0"><i class="bi bi-trash"></i></button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>

            </div>

        </div>
        <div class="col-4">
            <div class="card mt-3" style="min-width: 355px;">
                <div class="card-ab-header">
                    <h5>Add New Item</h5>
                </div>
                <div class="card-body">
                    <form action="<?= BASEURL ?>/admin/menu_add" method="POST" enctype="multipart/form-data">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="name" id="name" placeholder="Item Name">
                            <label for="name">Name</label>
                            <div class="text-danger mt-1">
                                <?php Validator::showError('name'); ?>
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <textarea class="form-control" name="description" id="description" placeholder="Item Description" style="height: 100px;"></textarea>
                            <label for="description">Description</label>
                            <div class="text-danger mt-1">
                                <?php Validator::showError('description'); ?>
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <select name="category_id" id="category_id" class="form-select">
                                <?php foreach ($data['categories'] as $category) : ?>
                                    <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
                                <?php endforeach ?>
                            </select>
                            <label for="category_id">Category</label>
                            <div class="text-danger mt-1">
                                <?php Validator::showError('category_id'); ?>
                            </div>
                        </div>
                        <div class="input-group">
                            <span class="input-group-text" id="price">Rp.</span>
                            <input type="text" name="price" class="form-control" placeholder="Price" aria-label="price" aria-describedby="price">
                        </div>
                        <div class="text-danger mt-1">
                            <?php Validator::showError('price'); ?>
                        </div>
                        <div class="mt-3 mb-5">
                            <label for="image" class="form-label">Upload Image</label>
                            <input type="file" name="image" id="image" class="form-control">
                            <div class="text-danger mt-1">
                                <?php Validator::showError('image'); ?>
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-ab-square"><i class="bi bi-plus-lg me-2"></i> Add Item</button>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>




</section>