<h1>MANAGE MENU</h1>

<?php Flasher::flash(); ?>

<form action="<?= BASEURL ?>/admin/menu_add" method="POST" enctype="multipart/form-data">
    <div>
        <label for="name">Name</label>
        <input type="text" name="name" id="name">
    </div>
    <div>
        <label for="description">Description</label>
        <textarea name="description" id="description" cols="30" rows="10"></textarea>
    </div>

    <div>
        <label for="category_id">Category</label>
        <select name="category_id" id="category_id">
            <?php foreach( $data['categories'] as $category ): ?>
                <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div>
        <label for="price">Price</label>
        <input type="text" name="price" id="price">
    </div>

    <div>
        <label for="image">Image</label>
        <input type="file" name="image" id="image">
    </div>
    <button type="submit">Add Menu Item</button>
</form>
<br><br>
<?php foreach( $data['items'] as $item ): ?>
    <p><?= $item['name'] ?></p>
    <ul>
        <li>Price: <?= $item['price'] ?></li>
        <li>Category: <?= $item['category_id'] ?></li>
        <li><a href="<?= BASEURL ?>/admin/menu_details/<?= $item['id'] ?>">edit</a></li>
        <li><a href="<?= BASEURL ?>/admin/menu_delete/<?= $item['id'] ?>">delete</a></li>
    </ul>
<?php endforeach ?>