<section>
    <div class="container py-5">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <span class="heading">
                    <h2>CONTACT US</h2>
                </span>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-8 col-lg-6">
                <form action="<?= BASEURL ?>/home/sendMessage/" method="POST">
                    <div class="mb-3">
                        <label for="subject" class="form-label">Subject</label>
                        <input type="text" class="form-control" id="subject" name="subject">
                        <div class="text-danger mt-1">
                            <?php Validator::showError('subject'); ?>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name">
                        <div class="text-danger mt-1">
                            <?php Validator::showError('name'); ?>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email Address</label>
                        <input type="email" class="form-control" id="email" name="email">
                        <div class="text-danger mt-1">
                            <?php Validator::showError('email'); ?>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="number" class="form-label">Phone Number <span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" id="number" name="number">
                        <div class="text-danger mt-1">
                            <?php Validator::showError('number'); ?>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Message</label>
                        <textarea name="message" id="message" class="form-control" cols="30" rows="10"></textarea>
                        <div class="text-danger mt-1">
                            <?php Validator::showError('message'); ?>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-ab-orange" style="width: 40%">SEND</button>
                    </div>

                </form>
            </div>
        </div>

    </div>

</section>